import "./globals.css";

export const metadata = {
  title: {
    template: "%s - Zenn記事一覧",
    default: "Zenn記事一覧",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body className="text-[#083c49] bg-gradient-to-t from-[#baf3fd] to-[#0ed1e9]">
        <main className="w-[calc(100%-48px)]  lg:w-[calc(100%-80px)] mx-auto py-16">
          {children}
        </main>
      </body>
    </html>
  );
}
