import "./globals.css";

export const metadata = {
  title: {
    template: "%s - Zenn記事一覧",
    default: "Zenn記事一覧",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body className="text-[#4f4f4f] bg-gradient-to-t from-[#B0B0B0] to-[#E7E7E7]">
        <main className="w-[calc(100%-48px)]  lg:w-[calc(100%-80px)] mx-auto">{children}</main>
      </body>
    </html>
  );
}
